dotnet run --configuration Release --project MetaActions.Train -- \
	--domains\
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/domain.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/domain.pddl \
	--train-problems\
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p30.pddl \
	--test-problems\
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/blocksworld/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/childsnack/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/depots/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/driverlog/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/freecell/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/grid/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/gripper/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/hiking/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/miconic/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/mprime/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-notankage/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/pipesworld-tankage/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/rovers/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/satellite/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p07.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/snake/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p24.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/termes/p30.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p02.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p08.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p10.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p14.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p17.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p18.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p28.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tidybot/p29.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p01.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p03.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p04.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p05.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p06.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p09.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p11.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p12.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p13.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p15.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p16.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p19.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p20.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p21.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p22.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p23.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p25.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p26.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p27.pddl \
						 ../Dependencies/autoscale-benchmarks/21.11-agile-strips/tpp/p30.pddl \
	--generation-strategy PreconditionMetaActions\
	--verification-strategy Weak1m\
	--multitask\
	--timelimit 120\
	--rebuild
cp output/train/*.zip "TestingSets/all_p10_PreconditionMetaActions_Weak1m_120m.zip"
