dotnet run --configuration Release --project MetaActions.Train -- \
	--domains\
						 ../Dependencies/learning-benchmarks/blocksworld/domain.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/domain.pddl \
						 ../Dependencies/learning-benchmarks/ferry/domain.pddl \
						 ../Dependencies/learning-benchmarks/floortile/domain.pddl \
						 ../Dependencies/learning-benchmarks/miconic/domain.pddl \
						 ../Dependencies/learning-benchmarks/rovers/domain.pddl \
						 ../Dependencies/learning-benchmarks/satellite/domain.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/domain.pddl \
						 ../Dependencies/learning-benchmarks/spanner/domain.pddl \
						 ../Dependencies/learning-benchmarks/transport/domain.pddl \
	--train-problems\
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p31.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p32.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p33.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p33.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p35.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p37.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p38.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p38.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p39.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p40.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p44.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p44.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p45.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p46.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p48.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p49.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p51.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p52.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p52.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p53.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p55.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p55.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p57.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p57.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p58.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p59.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p60.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p60.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p62.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p64.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p65.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p67.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p67.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p68.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p70.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p71.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p72.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p74.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p75.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p76.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p77.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p77.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p78.pddl \
						 ../Dependencies/learning-benchmarks/floortile/training/easy/p78.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p78.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p79.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p80.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p82.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p83.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p84.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p85.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p85.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p86.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p86.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p87.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p87.pddl \
						 ../Dependencies/learning-benchmarks/rovers/training/easy/p90.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p92.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p92.pddl \
						 ../Dependencies/learning-benchmarks/spanner/training/easy/p93.pddl \
						 ../Dependencies/learning-benchmarks/transport/training/easy/p93.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/training/easy/p94.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/training/easy/p95.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/training/easy/p95.pddl \
						 ../Dependencies/learning-benchmarks/ferry/training/easy/p96.pddl \
						 ../Dependencies/learning-benchmarks/satellite/training/easy/p98.pddl \
						 ../Dependencies/learning-benchmarks/miconic/training/easy/p99.pddl \
	--test-problems\
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/blocksworld/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/childsnack/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/ferry/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/floortile/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/miconic/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/rovers/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/satellite/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/sokoban/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/spanner/testing/medium/p30.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p01.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p02.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p03.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p04.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p05.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p06.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p07.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p08.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p09.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p10.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p11.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p12.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p13.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p14.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p15.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p16.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p17.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p18.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p19.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p20.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p21.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p22.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p23.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p24.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p25.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p26.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p27.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p28.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p29.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/easy/p30.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p01.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p02.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p03.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p04.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p05.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p06.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p07.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p08.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p09.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p10.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p11.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p12.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p13.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p14.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p15.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p16.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p17.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p18.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p19.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p20.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p21.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p22.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p23.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p24.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p25.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p26.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p27.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p28.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p29.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/hard/p30.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p01.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p02.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p03.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p04.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p05.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p06.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p07.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p08.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p09.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p10.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p11.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p12.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p13.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p14.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p15.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p16.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p17.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p18.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p19.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p20.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p21.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p22.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p23.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p24.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p25.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p26.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p27.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p28.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p29.pddl \
						 ../Dependencies/learning-benchmarks/transport/testing/medium/p30.pddl \
	--generation-strategy PreconditionMetaActions\
	--verification-strategy Weak15m\
	--multitask\
	--timelimit 360\
	--rebuild
cp output/train/*.zip "TestingSets/IPC_p10_PreconditionMetaActions_Weak15m_360m.zip"
